POST http://localhost:9090/api/v1/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTc5OTU0NzAsInVzZXJJZCI6Mn0.-eMXwMnifJL32398ZpQoFSMAsp_0PLmqpwMbd6g-ZC8

{
    "name": "AI Conference",
    "description": "Emerging Market AI Conferencet",
    "Location": "Des Moines, Iowa",
    "datetime": "2025-01-05T10:30:00.0000Z"
}    
