POST http://localhost:9090/api/v1/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthbGlnc0BnbWFpbC5jb20iLCJleHAiOjE3MTc5NTcxMzMsInVzZXJJZCI6MX0.iq5a61Tn5rKlTotp-D7zaOpnmybdDJt4cWvyOEQCSKA

{
    "name": "AI Conference",
    "description": "Theme: State of the AI in 2024, Fairfield IA",
    "location": "Iowa, USA",
    "datetime": "2024-07-01T12:00:00.000Z"
}
    
